"""two

Revision ID: b9cd500884ec
Revises: eaee0b4a1ceb
Create Date: 2022-10-03 17:41:19.295217

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b9cd500884ec'
down_revision = 'eaee0b4a1ceb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'records',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('master', sa.VARCHAR(length=100), nullable=False),
        sa.Column('record_time', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records')
    # ### end Alembic commands ###
