"""

Revision ID: fb36eaeae925
Revises: a7160f6ea833
Create Date: 2022-10-05 19:13:40.245614

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'fb36eaeae925'
down_revision = 'a7160f6ea833'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'feedback',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('master', sa.VARCHAR(length=100), nullable=True),
        sa.Column('feedback', sa.VARCHAR(length=1500), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    # ### end Alembic commands ###
